/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Appointment {
  assistant_id: string | null;
  booking_channel: Generated<string>;
  chair_id: string | null;
  created_at: Generated<string>;
  created_by: string | null;
  doctor_id: string;
  duration_minutes: Generated<number>;
  followed_up_by: string | null;
  id: string | null;
  notes: string | null;
  person_id: string;
  scheduled_at: string;
  status: Generated<string>;
  type: string;
}

export interface AppUser {
  address: string | null;
  created_at: Generated<string>;
  date_of_birth: string | null;
  email: string | null;
  full_name: string;
  id: string | null;
  national_id: string | null;
  phone: string;
  role: string;
  status: Generated<string>;
  verified_at: string | null;
  verified_by: string | null;
}

export interface AttendanceLog {
  clock_in: string;
  clock_out: string | null;
  date: string;
  id: string | null;
  notes: string | null;
  payroll_record_id: string | null;
  staff_id: string;
  total_minutes: number | null;
}

export interface Chair {
  chair_type_id: string;
  code: string;
  display_order: Generated<number>;
  id: string | null;
  notes: string | null;
  status: Generated<string>;
}

export interface ChairType {
  description: string | null;
  id: string | null;
  name: string;
}

export interface CommissionEntry {
  amount: number;
  commission_base: number;
  commission_rule_id: string;
  earned_at: Generated<string>;
  id: string | null;
  payroll_record_id: string | null;
  performance_log_id: string | null;
  session_id: string | null;
  source_type: string;
  staff_id: string;
  status: Generated<string>;
}

export interface CommissionRule {
  commission_type: string;
  commission_value: number;
  effective_from: string;
  event_type: string | null;
  id: string | null;
  notes: string | null;
  role: string;
  service_category_id: string | null;
  set_by: string;
  staff_id: string | null;
}

export interface DiscountProposal {
  discount_type: string;
  discount_value: number;
  id: string | null;
  proposed_by: string;
  reason: string;
  review_note: string | null;
  reviewed_at: string | null;
  reviewed_by: string | null;
  status: Generated<string>;
  treatment_plan_id: string;
}

export interface DoctorSchedule {
  date: string | null;
  day_of_week: number | null;
  doctor_id: string;
  end_time: string;
  id: string | null;
  is_available: Generated<number>;
  note: string | null;
  start_time: string;
}

export interface Equipment {
  id: string | null;
  location: string | null;
  name: string;
  notes: string | null;
  purchase_cost: number | null;
  purchase_date: string | null;
  retired_on: string | null;
  serial_number: string | null;
  status: Generated<string>;
  vendor_id: string | null;
}

export interface EquipmentMaintenance {
  cost: number | null;
  equipment_id: string;
  id: string | null;
  next_due_date: string | null;
  notes: string | null;
  performed_at: string;
  performed_by: string | null;
  type: string;
  vendor_id: string | null;
}

export interface HealthRecord {
  allergies: string | null;
  blood_type: string | null;
  current_medications: string | null;
  dental_history: string | null;
  id: string | null;
  last_updated_at: string | null;
  last_updated_by: string | null;
  medical_conditions: string | null;
  patient_id: string;
}

export interface InventoryBatch {
  expiry_date: string;
  id: string | null;
  inventory_item_id: string;
  lot_number: string;
  quantity_received: number;
  quantity_remaining: number;
  received_at: Generated<string>;
  unit_cost: number;
  vendor_id: string | null;
}

export interface InventoryItem {
  category: Generated<string>;
  id: string | null;
  last_restocked_at: string | null;
  name: string;
  quantity_on_hand: Generated<number>;
  reorder_threshold: Generated<number>;
  unit: string;
  vendor_id: string | null;
}

export interface InventoryLog {
  batch_id: string;
  change_type: string;
  id: string | null;
  inventory_item_id: string;
  logged_at: Generated<string>;
  logged_by: string;
  notes: string | null;
  quantity_after: number;
  quantity_delta: number;
  related_procedure_id: string | null;
}

export interface Invoice {
  discount_amount: Generated<number>;
  discount_proposal_id: string | null;
  due_date: string | null;
  id: string | null;
  invoice_number: string | null;
  invoice_serial: string | null;
  issued_at: string | null;
  patient_id: string;
  promotion_code: string | null;
  promotion_id: string | null;
  status: Generated<string>;
  subtotal: Generated<number>;
  tax_authority_code: string | null;
  total: Generated<number>;
  treatment_plan_id: string;
  vat_total: Generated<number>;
}

export interface InvoiceLine {
  credits_line_id: string | null;
  description: string;
  discount_amount: Generated<number>;
  id: string | null;
  invoice_id: string;
  issued_at: Generated<string>;
  line_total: number;
  procedure_id: string | null;
  quantity: Generated<number>;
  session_id: string | null;
  surfaces: string | null;
  tooth_codes: string | null;
  unit_price: number;
  vat_amount: Generated<number>;
  vat_rate: Generated<number>;
}

export interface MaterialOption {
  description: string | null;
  display_order: Generated<number>;
  id: string | null;
  is_active: Generated<number>;
  name: string;
  service_category_id: string;
}

export interface Notification {
  body: string;
  id: string | null;
  is_read: Generated<number>;
  read_at: string | null;
  recipient_id: string | null;
  recipient_role: string | null;
  related_entity_id: string | null;
  related_entity_type: string | null;
  sender_id: string | null;
  sent_at: Generated<string>;
  title: string;
  type: string;
}

export interface PatientMedia {
  file_url: string;
  id: string | null;
  notes: string | null;
  patient_id: string;
  procedure_id: string | null;
  stage: string | null;
  taken_at: string | null;
  type: string;
  uploaded_by: string;
}

export interface PatientProfile {
  created_at: Generated<string>;
  created_by: string;
  emergency_contact: string | null;
  id: string | null;
  referral_source: string | null;
  user_id: string;
}

export interface Payment {
  amount: number;
  direction: Generated<string>;
  id: string | null;
  invoice_id: string;
  method: string;
  notes: string | null;
  paid_at: Generated<string>;
  received_by: string;
  reference_number: string | null;
}

export interface PayrollAdjustment {
  amount: number;
  created_at: Generated<string>;
  created_by: string;
  direction: string;
  id: string | null;
  payroll_record_id: string | null;
  reason: string;
  related_commission_entry_id: string | null;
  related_failure_id: string | null;
  related_invoice_id: string | null;
  staff_id: string;
  status: Generated<string>;
}

export interface PayrollRecord {
  approved_at: string | null;
  approved_by: string | null;
  base_pay: Generated<number>;
  commission_total: Generated<number>;
  id: string | null;
  net_pay: Generated<number>;
  notes: string | null;
  paid_at: string | null;
  period_end: string;
  period_start: string;
  staff_id: string;
  status: Generated<string>;
  total_credits: Generated<number>;
  total_debits: Generated<number>;
  total_hours_worked: Generated<number>;
}

export interface PriceList {
  currency: Generated<string>;
  effective_from: string;
  id: string | null;
  material_option_id: string | null;
  notes: string | null;
  service_category_id: string;
  set_by: string;
  unit_price: number;
}

export interface ProcedureDecision {
  decided_at: Generated<string>;
  decided_by: string;
  from_status: string | null;
  id: string | null;
  note: string | null;
  procedure_id: string;
  reason: string | null;
  risk_explained: number | null;
  to_status: string;
}

export interface ProcedureInstruction {
  created_by: string;
  id: string | null;
  instructions: string | null;
  service_category_id: string;
  supplies_required: string | null;
  title: string;
  updated_at: Generated<string>;
  version: Generated<number>;
}

export interface ProcedureSession {
  appointment_id: string | null;
  assistant_id: string | null;
  billable_amount: number | null;
  completed_at: string | null;
  id: string | null;
  next_step_note: string | null;
  performed_by: string;
  procedure_id: string;
  progress_note: string | null;
  session_number: number;
  status: Generated<string>;
  vitals: string | null;
}

export interface ProcedureSupplyList {
  id: string | null;
  instruction_set_id: string | null;
  inventory_item_id: string;
  notes: string | null;
  procedure_id: string | null;
  quantity_required: number;
}

export interface ProcedureTooth {
  addresses_condition_id: string | null;
  id: string | null;
  note: string | null;
  procedure_id: string;
  role: string | null;
  surfaces: string | null;
  tooth_code: string;
}

export interface Promotion {
  code: string;
  created_by: string;
  discount_type: string;
  discount_value: number;
  end_date: string;
  id: string | null;
  is_active: Generated<number>;
  max_redemptions: number | null;
  name: string;
  notes: string | null;
  start_date: string;
}

export interface ReceptionistPerformanceLog {
  appointment_id: string | null;
  event_type: string;
  id: string | null;
  occurred_at: Generated<string>;
  patient_id: string;
  receptionist_id: string;
}

export interface ServiceCategory {
  description: string | null;
  display_order: Generated<number>;
  id: string | null;
  is_active: Generated<number>;
  is_special: Generated<number>;
  name: string;
  pricing_basis: Generated<string>;
  required_chair_type_id: string | null;
  requires_material_choice: Generated<number>;
  resulting_condition_type: string | null;
  tooth_scope: Generated<string>;
  vat_rate: Generated<number>;
  warranty_days: number | null;
}

export interface SpecialProcedureProposal {
  clinical_justification: string;
  estimated_cost: number | null;
  id: string | null;
  proposed_by: string;
  review_note: string | null;
  reviewed_at: string | null;
  reviewed_by: string | null;
  service_category_id: string;
  status: Generated<string>;
  treatment_plan_id: string;
}

export interface StaffProfile {
  employment_status: Generated<string>;
  end_date: string | null;
  id: string | null;
  join_date: string;
  license_number: string | null;
  specialty: string | null;
  user_id: string;
}

export interface SurfaceCombination {
  combo: string;
  valid_surfaces: string;
}

export interface Tooth {
  arch: string;
  code: string | null;
  dentition: string;
  is_anterior: number;
  name: string;
  name_vi: string;
  position: number;
  quadrant: number;
  side: string;
  tooth_type: string;
  universal_code: string | null;
  valid_surfaces: string;
}

export interface ToothCondition {
  condition_type: string;
  id: string | null;
  note: string | null;
  observed_at: Generated<string>;
  observed_by: string;
  observed_during_procedure_id: string | null;
  patient_id: string;
  resolved_at: string | null;
  severity: string | null;
  status: Generated<string>;
  surfaces: string | null;
  tooth_code: string;
}

export interface TreatmentFailure {
  clinical_finding: string | null;
  determination_note: string | null;
  determined_at: string | null;
  determined_by: string | null;
  examined_by: string;
  fault_attribution: string | null;
  id: string | null;
  patient_account: string;
  procedure_id: string;
  remedy: string | null;
  reported_at: Generated<string>;
  status: Generated<string>;
  tooth_code: string | null;
}

export interface TreatmentPlan {
  created_at: Generated<string>;
  doctor_id: string;
  estimated_end_date: string | null;
  id: string | null;
  is_special: Generated<number>;
  notes: string | null;
  patient_id: string;
  payment_mode: Generated<string>;
  start_date: string | null;
  status: Generated<string>;
  title: string;
  updated_at: Generated<string>;
}

export interface TreatmentProcedure {
  completed_date: string | null;
  doctor_note: string | null;
  id: string | null;
  instruction_set_id: string | null;
  material_option_id: string | null;
  planned_sessions: Generated<number>;
  remedy_for_failure_id: string | null;
  sequence: number;
  service_category_id: string;
  status: Generated<string>;
  treatment_plan_id: string;
  unit_price: number | null;
}

export interface VAppointmentOffRoster {
  at: string | null;
  doctor: string | null;
  id: string | null;
  scheduled_at: string | null;
  status: string | null;
}

export interface VAttendancePriced {
  date: string | null;
  hours: string | null;
  id: string | null;
  pay: string | null;
  payroll_record_id: string | null;
  rate_that_day: number | null;
  staff: string | null;
  total_minutes: number | null;
}

export interface VBookableChair {
  bookable: string | null;
  chair_type: string | null;
  code: string | null;
  id: string | null;
  status: string | null;
}

export interface VChairOccupancy {
  chair: string | null;
  chair_status: string | null;
  chair_type: string | null;
  doctor: string | null;
  occupancy: string | null;
  patient: string | null;
  scheduled_at: string | null;
}

export interface VCommissionDashboard {
  commission: string | null;
  entries: string | null;
  role: string | null;
  staff: string | null;
  status: string | null;
  total_base: string | null;
}

export interface VCommissionDetail {
  amount: number | null;
  commission_base: number | null;
  commission_type: string | null;
  commission_value: number | null;
  earned_at: string | null;
  earned_on: string | null;
  patient: string | null;
  role: string | null;
  rule_kind: string | null;
  rule_scope: string | null;
  source_type: string | null;
  staff: string | null;
  status: string | null;
  worked_as: string | null;
}

export interface VCurrentPrice {
  effective_from: string | null;
  is_special: number | null;
  material: string | null;
  material_option_id: string | null;
  price_source: string | null;
  service: string | null;
  service_category_id: string | null;
  unit_price: number | null;
  vat_rate: number | null;
}

export interface VCurrentWage {
  effective_from: string | null;
  employment_status: string | null;
  rate: number | null;
  reason: string | null;
  role: string | null;
  staff: string | null;
  staff_id: string | null;
  wage_type: string | null;
}

export interface VDaySheet {
  at: string | null;
  booking_channel: string | null;
  chair: string | null;
  day: string | null;
  doctor: string | null;
  mins: number | null;
  person: string | null;
  person_status: string | null;
  status: string | null;
  type: string | null;
}

export interface VDeclinedWork {
  declined_at: string | null;
  patient: string | null;
  reason: string | null;
  recorded_by: string | null;
  risk_explained: string | null;
  service: string | null;
}

export interface VDualProfile {
  employment_status: string | null;
  full_name: string | null;
  patient_id: string | null;
  role: string | null;
  staff_id: string | null;
}

export interface Vendor {
  address: string | null;
  contact_person: string | null;
  email: string | null;
  id: string | null;
  is_active: Generated<number>;
  name: string;
  notes: string | null;
  phone: string | null;
}

export interface VEquipmentStatus {
  last_serviced: string | null;
  location: string | null;
  name: string | null;
  next_due: string | null;
  purchase_cost: number | null;
  purchase_date: string | null;
  serial_number: string | null;
  state: string | null;
  status: string | null;
  vendor: string | null;
}

export interface VExpiredStock {
  days_overdue: string | null;
  expiry_date: string | null;
  item: string | null;
  lot_number: string | null;
  remaining: number | null;
  unit: string | null;
  value_at_risk: string | null;
}

export interface VFindingTreatment {
  addressed_by_n: string | null;
  condition_id: string | null;
  condition_type: string | null;
  finding_status: string | null;
  patient: string | null;
  procedures: string | null;
  surfaces: string | null;
  tooth: string | null;
}

export interface VIdentityFunnel {
  is_patient: string | null;
  is_staff: string | null;
  people: string | null;
  status: string | null;
  with_cccd: string | null;
  with_email: string | null;
}

export interface VInbox {
  addressed: string | null;
  body: string | null;
  is_read: number | null;
  notification_id: string | null;
  reader: string | null;
  related_entity_id: string | null;
  related_entity_type: string | null;
  sender: string | null;
  sent_at: string | null;
  title: string | null;
  type: string | null;
  user_id: string | null;
}

export interface VInvoiceBalance {
  balance_due: string | null;
  discount: number | null;
  invoice_id: string | null;
  legal_number: string | null;
  patient: string | null;
  plan: string | null;
  received: string | null;
  refunded: string | null;
  status: string | null;
  subtotal: number | null;
  total: number | null;
  vat: number | null;
}

export interface VInvoiceDetail {
  description: string | null;
  discount: number | null;
  gross: number | null;
  invoice_id: string | null;
  kind: string | null;
  line_charge: string | null;
  net: string | null;
  patient: string | null;
  quantity: number | null;
  surfaces: string | null;
  teeth: string | null;
  unit_price: number | null;
  vat: number | null;
  vat_rate: string | null;
}

export interface VLowStock {
  contact_person: string | null;
  item: string | null;
  on_hand: number | null;
  phone: string | null;
  reorder_at: number | null;
  state: string | null;
  unit: string | null;
  vendor: string | null;
}

export interface VNotificationContext {
  about: string | null;
  context: string | null;
  id: string | null;
  is_read: number | null;
  sent_at: string | null;
  title: string | null;
  to_whom: string | null;
  type: string | null;
}

export interface VPayslip {
  approved_by: string | null;
  base_pay: number | null;
  commission: number | null;
  credits: number | null;
  debits: number | null;
  hours: number | null;
  net_pay: number | null;
  period_end: string | null;
  period_start: string | null;
  role: string | null;
  staff: string | null;
  status: string | null;
}

export interface VPendingApprovals {
  amount: number | null;
  detail: string | null;
  id: string | null;
  kind: string | null;
  patient: string | null;
  plan: string | null;
  proposed_by: string | null;
}

export interface VPendingChases {
  about: string | null;
  chase: string | null;
  dated: string | null;
  person: string | null;
  phone: string | null;
}

export interface VPickOrder {
  days_to_expiry: string | null;
  expiry_date: string | null;
  item: string | null;
  lot_number: string | null;
  pick_next: string | null;
  remaining: number | null;
  state: string | null;
  unit_cost: number | null;
}

export interface VPlanDetail {
  completed_date: string | null;
  lead_doctor: string | null;
  material: string | null;
  patient: string | null;
  payment_mode: string | null;
  plan_id: string | null;
  plan_status: string | null;
  planned_sessions: number | null;
  procedure_status: string | null;
  sequence: number | null;
  service: string | null;
  title: string | null;
}

export interface VPortalAccess {
  employment: string | null;
  full_name: string | null;
  id: string | null;
  patient_portal: string | null;
  role: string | null;
  staff_portal: string | null;
  status: string | null;
}

export interface VProcedureMaterialCost {
  cost: string | null;
  item: string | null;
  patient: string | null;
  procedure_id: string | null;
  service: string | null;
  unit: string | null;
  unit_cost: number | null;
  used: string | null;
}

export interface VProcedureTrail {
  decided_at: string | null;
  decided_by: string | null;
  procedure_id: string | null;
  reason: string | null;
  risk_explained: string | null;
  service: string | null;
  transition: string | null;
}

export interface VPromotionStatus {
  code: string | null;
  discount_type: string | null;
  discount_value: number | null;
  end_date: string | null;
  max_redemptions: number | null;
  name: string | null;
  start_date: string | null;
  state: string | null;
}

export interface VRescheduleFollowup {
  booking_channel: string | null;
  days_since: string | null;
  email: string | null;
  full_name: string | null;
  missed_appointment_id: string | null;
  missed_at: string | null;
  person_id: string | null;
  phone: string | null;
}

export interface VSessionLog {
  assistant: string | null;
  billable: string | null;
  completed_at: string | null;
  n: number | null;
  of_n: number | null;
  patient: string | null;
  performed_by: string | null;
  service: string | null;
  status: string | null;
  visit: string | null;
}

export interface VSupplyVariance {
  actual_total: string | null;
  expected_total: string | null;
  item: string | null;
  per_procedure: number | null;
  procedures: string | null;
  service: string | null;
  unit: string | null;
  variance: string | null;
}

export interface VToothChart {
  as_of: string | null;
  condition_type: string | null;
  layer: string | null;
  patient: string | null;
  patient_id: string | null;
  severity: string | null;
  status: string | null;
  surfaces: string | null;
  tooth: string | null;
  tooth_name: string | null;
}

export interface VTreatmentFailure {
  credited: string | null;
  determination_note: string | null;
  determined_by: string | null;
  failed_service: string | null;
  fault_attribution: string | null;
  id: string | null;
  patient: string | null;
  remedy: string | null;
  reported_at: string | null;
  rework_procedures: string | null;
  status: string | null;
  tooth: string | null;
}

export interface VUnreadCount {
  reader: string | null;
  unread: string | null;
  user_id: string | null;
}

export interface VUnsettled {
  amount: number | null;
  dated: string | null;
  kind: string | null;
  reason: string | null;
  staff: string | null;
}

export interface VVatCheck {
  discount: string | null;
  gross: string | null;
  invoice_id: string | null;
  overcharge_avoided: string | null;
  vat_charged: string | null;
  vat_if_charged_on_gross: string | null;
}

export interface WageRate {
  effective_from: string;
  id: string | null;
  rate: number;
  reason: string | null;
  set_by: string;
  staff_id: string;
  wage_type: string;
}

export interface DB {
  app_user: AppUser;
  appointment: Appointment;
  attendance_log: AttendanceLog;
  chair: Chair;
  chair_type: ChairType;
  commission_entry: CommissionEntry;
  commission_rule: CommissionRule;
  discount_proposal: DiscountProposal;
  doctor_schedule: DoctorSchedule;
  equipment: Equipment;
  equipment_maintenance: EquipmentMaintenance;
  health_record: HealthRecord;
  inventory_batch: InventoryBatch;
  inventory_item: InventoryItem;
  inventory_log: InventoryLog;
  invoice: Invoice;
  invoice_line: InvoiceLine;
  material_option: MaterialOption;
  notification: Notification;
  patient_media: PatientMedia;
  patient_profile: PatientProfile;
  payment: Payment;
  payroll_adjustment: PayrollAdjustment;
  payroll_record: PayrollRecord;
  price_list: PriceList;
  procedure_decision: ProcedureDecision;
  procedure_instruction: ProcedureInstruction;
  procedure_session: ProcedureSession;
  procedure_supply_list: ProcedureSupplyList;
  procedure_tooth: ProcedureTooth;
  promotion: Promotion;
  receptionist_performance_log: ReceptionistPerformanceLog;
  service_category: ServiceCategory;
  special_procedure_proposal: SpecialProcedureProposal;
  staff_profile: StaffProfile;
  surface_combination: SurfaceCombination;
  tooth: Tooth;
  tooth_condition: ToothCondition;
  treatment_failure: TreatmentFailure;
  treatment_plan: TreatmentPlan;
  treatment_procedure: TreatmentProcedure;
  v_appointment_off_roster: VAppointmentOffRoster;
  v_attendance_priced: VAttendancePriced;
  v_bookable_chair: VBookableChair;
  v_chair_occupancy: VChairOccupancy;
  v_commission_dashboard: VCommissionDashboard;
  v_commission_detail: VCommissionDetail;
  v_current_price: VCurrentPrice;
  v_current_wage: VCurrentWage;
  v_day_sheet: VDaySheet;
  v_declined_work: VDeclinedWork;
  v_dual_profile: VDualProfile;
  v_equipment_status: VEquipmentStatus;
  v_expired_stock: VExpiredStock;
  v_finding_treatment: VFindingTreatment;
  v_identity_funnel: VIdentityFunnel;
  v_inbox: VInbox;
  v_invoice_balance: VInvoiceBalance;
  v_invoice_detail: VInvoiceDetail;
  v_low_stock: VLowStock;
  v_notification_context: VNotificationContext;
  v_payslip: VPayslip;
  v_pending_approvals: VPendingApprovals;
  v_pending_chases: VPendingChases;
  v_pick_order: VPickOrder;
  v_plan_detail: VPlanDetail;
  v_portal_access: VPortalAccess;
  v_procedure_material_cost: VProcedureMaterialCost;
  v_procedure_trail: VProcedureTrail;
  v_promotion_status: VPromotionStatus;
  v_reschedule_followup: VRescheduleFollowup;
  v_session_log: VSessionLog;
  v_supply_variance: VSupplyVariance;
  v_tooth_chart: VToothChart;
  v_treatment_failure: VTreatmentFailure;
  v_unread_count: VUnreadCount;
  v_unsettled: VUnsettled;
  v_vat_check: VVatCheck;
  vendor: Vendor;
  wage_rate: WageRate;
}
